apiVersion: v1
kind: ConfigMap
metadata:
  name: pharma-ui
  namespace: dev
  labels:
    app: pharma-ui
    version: "1.0.0"
data:
  API_BASE_URL: "http://localhost:8081/api"
  AUTH_BASE_URL: "http://localhost:8081/auth"
  ENV: dev
